#!/usr/bin/env ruby
# Script to generate GRUB files from a simple configuration file

require 'yaml'

CONF = YAML.load($stdin.read)

def entry num
    e = CONF['entries'][num]
    raise 'no such entry' unless e
    title = e.keys[0]
    e = e[title]
    a = []
    a << "# [#{num}] #{e['root']}"
    a << "title #{title}"
    a << "root#{'noverify' if e['verify']==false} #{e['root']}"
    a << "kernel #{e['kernel']} #{e['kernel options']}" if e['kernel']
    a << "initrd #{e['initrd']}" if e['initrd']
    a << "chainloader +1" if e['special'] == 'chainloader'
    a << "savedefault"
    return a.join("\n")
end

def entries
    a = []
    CONF['entries'].each_with_index do |it,id|
        a << entry(id)
    end
    return a.join("\n\n")
end

case ARGV.shift
when 'genlogon'
    print <<-EOF
# Generated by MAW-GENLOGON
default 0
color #{CONF['logon colors']||"white/red white/black"}
password #{CONF['password']} #{CONF['main menu file']}

title Please authenticate to continue
lock
EOF
when 'autoboot'
    print <<-EOF
# Generated by MAW-AUTOBOOT
default 0
timeout 0

#{entry ARGV.shift.to_i}
EOF
when 'genmenu'
    print <<-EOF
# Generated by MAW-GENMENU
default saved
timeout #{CONF['timeout']||5}
color #{CONF['main menu colors']||"white/green white/black"}
#{"splashimage #{CONF['background']}" if CONF['background']}

#{entries}
EOF
end

